// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID                      uuid.UUID          `json:"id"`
	ShopID                  uuid.UUID          `json:"shop_id"`
	GithubIssueNumber       int32              `json:"github_issue_number"`
	OrderNumber             int32              `json:"order_number"`
	GithubIssueUrl          pgtype.Text        `json:"github_issue_url"`
	GithubUsername          string             `json:"github_username"`
	Sku                     string             `json:"sku"`
	Options                 []byte             `json:"options"`
	SubtotalCents           int32              `json:"subtotal_cents"`
	ShippingCents           int32              `json:"shipping_cents"`
	TaxCents                pgtype.Int4        `json:"tax_cents"`
	TotalCents              int32              `json:"total_cents"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   pgtype.Text        `json:"stripe_payment_intent_id"`
	CustomerEmail           pgtype.Text        `json:"customer_email"`
	CustomerName            pgtype.Text        `json:"customer_name"`
	ShippingAddress         []byte             `json:"shipping_address"`
	TrackingNumber          pgtype.Text        `json:"tracking_number"`
	TrackingUrl             pgtype.Text        `json:"tracking_url"`
	Carrier                 pgtype.Text        `json:"carrier"`
	FailureReason           pgtype.Text        `json:"failure_reason"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	ShippedAt               pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt             pgtype.Timestamptz `json:"delivered_at"`
}

type Shop struct {
	ID                   uuid.UUID `json:"id"`
	GithubInstallationID int64     `json:"github_installation_id"`
	// GitHub repository ID (numeric) - immutable and unique, used as primary lookup key
	GithubRepoID int64 `json:"github_repo_id"`
	// GitHub repository full name (e.g., owner/repo) - for display only, can change
	GithubRepoFullName     string             `json:"github_repo_full_name"`
	OwnerEmail             string             `json:"owner_email"`
	EmailProvider          pgtype.Text        `json:"email_provider"`
	EmailConfig            []byte             `json:"email_config"`
	EmailVerified          pgtype.Bool        `json:"email_verified"`
	StripeConnectAccountID pgtype.Text        `json:"stripe_connect_account_id"`
	DisconnectedAt         pgtype.Timestamptz `json:"disconnected_at"`
	OnboardedAt            pgtype.Timestamptz `json:"onboarded_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}
