// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    shop_id, github_issue_number, order_number, github_issue_url, github_username, sku,
    options, subtotal_cents, shipping_cents, tax_cents, total_cents,
    stripe_checkout_session_id, customer_email, customer_name, shipping_address, status
) VALUES (
    $1, $2, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
RETURNING id, shop_id, github_issue_number, order_number, github_issue_url, github_username, sku,
          options, subtotal_cents, shipping_cents, tax_cents, total_cents,
          stripe_checkout_session_id, stripe_payment_intent_id, customer_email, customer_name,
          shipping_address, tracking_number, tracking_url, carrier, status,
          created_at, paid_at, shipped_at, delivered_at
`

type CreateOrderParams struct {
	ShopID                  uuid.UUID   `json:"shop_id"`
	GithubIssueNumber       int32       `json:"github_issue_number"`
	GithubIssueUrl          pgtype.Text `json:"github_issue_url"`
	GithubUsername          string      `json:"github_username"`
	Sku                     string      `json:"sku"`
	Options                 []byte      `json:"options"`
	SubtotalCents           int32       `json:"subtotal_cents"`
	ShippingCents           int32       `json:"shipping_cents"`
	TaxCents                pgtype.Int4 `json:"tax_cents"`
	TotalCents              int32       `json:"total_cents"`
	StripeCheckoutSessionID pgtype.Text `json:"stripe_checkout_session_id"`
	CustomerEmail           pgtype.Text `json:"customer_email"`
	CustomerName            pgtype.Text `json:"customer_name"`
	ShippingAddress         []byte      `json:"shipping_address"`
	Status                  string      `json:"status"`
}

type CreateOrderRow struct {
	ID                      uuid.UUID          `json:"id"`
	ShopID                  uuid.UUID          `json:"shop_id"`
	GithubIssueNumber       int32              `json:"github_issue_number"`
	OrderNumber             int32              `json:"order_number"`
	GithubIssueUrl          pgtype.Text        `json:"github_issue_url"`
	GithubUsername          string             `json:"github_username"`
	Sku                     string             `json:"sku"`
	Options                 []byte             `json:"options"`
	SubtotalCents           int32              `json:"subtotal_cents"`
	ShippingCents           int32              `json:"shipping_cents"`
	TaxCents                pgtype.Int4        `json:"tax_cents"`
	TotalCents              int32              `json:"total_cents"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   pgtype.Text        `json:"stripe_payment_intent_id"`
	CustomerEmail           pgtype.Text        `json:"customer_email"`
	CustomerName            pgtype.Text        `json:"customer_name"`
	ShippingAddress         []byte             `json:"shipping_address"`
	TrackingNumber          pgtype.Text        `json:"tracking_number"`
	TrackingUrl             pgtype.Text        `json:"tracking_url"`
	Carrier                 pgtype.Text        `json:"carrier"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	ShippedAt               pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt             pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ShopID,
		arg.GithubIssueNumber,
		arg.GithubIssueUrl,
		arg.GithubUsername,
		arg.Sku,
		arg.Options,
		arg.SubtotalCents,
		arg.ShippingCents,
		arg.TaxCents,
		arg.TotalCents,
		arg.StripeCheckoutSessionID,
		arg.CustomerEmail,
		arg.CustomerName,
		arg.ShippingAddress,
		arg.Status,
	)
	var i CreateOrderRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.GithubIssueNumber,
		&i.OrderNumber,
		&i.GithubIssueUrl,
		&i.GithubUsername,
		&i.Sku,
		&i.Options,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.ShippingAddress,
		&i.TrackingNumber,
		&i.TrackingUrl,
		&i.Carrier,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, shop_id, github_issue_number, order_number, github_issue_url, github_username, sku,
       options, subtotal_cents, shipping_cents, tax_cents, total_cents,
       stripe_checkout_session_id, stripe_payment_intent_id, customer_email, customer_name,
       shipping_address, tracking_number, tracking_url, carrier, status,
       created_at, paid_at, shipped_at, delivered_at
FROM orders
WHERE id = $1
`

type GetOrderByIDRow struct {
	ID                      uuid.UUID          `json:"id"`
	ShopID                  uuid.UUID          `json:"shop_id"`
	GithubIssueNumber       int32              `json:"github_issue_number"`
	OrderNumber             int32              `json:"order_number"`
	GithubIssueUrl          pgtype.Text        `json:"github_issue_url"`
	GithubUsername          string             `json:"github_username"`
	Sku                     string             `json:"sku"`
	Options                 []byte             `json:"options"`
	SubtotalCents           int32              `json:"subtotal_cents"`
	ShippingCents           int32              `json:"shipping_cents"`
	TaxCents                pgtype.Int4        `json:"tax_cents"`
	TotalCents              int32              `json:"total_cents"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   pgtype.Text        `json:"stripe_payment_intent_id"`
	CustomerEmail           pgtype.Text        `json:"customer_email"`
	CustomerName            pgtype.Text        `json:"customer_name"`
	ShippingAddress         []byte             `json:"shipping_address"`
	TrackingNumber          pgtype.Text        `json:"tracking_number"`
	TrackingUrl             pgtype.Text        `json:"tracking_url"`
	Carrier                 pgtype.Text        `json:"carrier"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	ShippedAt               pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt             pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.GithubIssueNumber,
		&i.OrderNumber,
		&i.GithubIssueUrl,
		&i.GithubUsername,
		&i.Sku,
		&i.Options,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.ShippingAddress,
		&i.TrackingNumber,
		&i.TrackingUrl,
		&i.Carrier,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getOrderByIssueNumber = `-- name: GetOrderByIssueNumber :one
SELECT id, shop_id, github_issue_number, order_number, github_issue_url, github_username, sku,
       options, subtotal_cents, shipping_cents, tax_cents, total_cents,
       stripe_checkout_session_id, stripe_payment_intent_id, customer_email, customer_name,
       shipping_address, tracking_number, tracking_url, carrier, status,
       created_at, paid_at, shipped_at, delivered_at
FROM orders
WHERE shop_id = $1 AND github_issue_number = $2
`

type GetOrderByIssueNumberParams struct {
	ShopID            uuid.UUID `json:"shop_id"`
	GithubIssueNumber int32     `json:"github_issue_number"`
}

type GetOrderByIssueNumberRow struct {
	ID                      uuid.UUID          `json:"id"`
	ShopID                  uuid.UUID          `json:"shop_id"`
	GithubIssueNumber       int32              `json:"github_issue_number"`
	OrderNumber             int32              `json:"order_number"`
	GithubIssueUrl          pgtype.Text        `json:"github_issue_url"`
	GithubUsername          string             `json:"github_username"`
	Sku                     string             `json:"sku"`
	Options                 []byte             `json:"options"`
	SubtotalCents           int32              `json:"subtotal_cents"`
	ShippingCents           int32              `json:"shipping_cents"`
	TaxCents                pgtype.Int4        `json:"tax_cents"`
	TotalCents              int32              `json:"total_cents"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   pgtype.Text        `json:"stripe_payment_intent_id"`
	CustomerEmail           pgtype.Text        `json:"customer_email"`
	CustomerName            pgtype.Text        `json:"customer_name"`
	ShippingAddress         []byte             `json:"shipping_address"`
	TrackingNumber          pgtype.Text        `json:"tracking_number"`
	TrackingUrl             pgtype.Text        `json:"tracking_url"`
	Carrier                 pgtype.Text        `json:"carrier"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	ShippedAt               pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt             pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) GetOrderByIssueNumber(ctx context.Context, arg GetOrderByIssueNumberParams) (GetOrderByIssueNumberRow, error) {
	row := q.db.QueryRow(ctx, getOrderByIssueNumber, arg.ShopID, arg.GithubIssueNumber)
	var i GetOrderByIssueNumberRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.GithubIssueNumber,
		&i.OrderNumber,
		&i.GithubIssueUrl,
		&i.GithubUsername,
		&i.Sku,
		&i.Options,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.ShippingAddress,
		&i.TrackingNumber,
		&i.TrackingUrl,
		&i.Carrier,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getOrderByStripeSessionID = `-- name: GetOrderByStripeSessionID :one
SELECT id, shop_id, github_issue_number, order_number, github_issue_url, github_username, sku,
       options, subtotal_cents, shipping_cents, tax_cents, total_cents,
       stripe_checkout_session_id, stripe_payment_intent_id, customer_email, customer_name,
       shipping_address, tracking_number, tracking_url, carrier, status,
       created_at, paid_at, shipped_at, delivered_at
FROM orders 
WHERE stripe_checkout_session_id = $1
`

type GetOrderByStripeSessionIDRow struct {
	ID                      uuid.UUID          `json:"id"`
	ShopID                  uuid.UUID          `json:"shop_id"`
	GithubIssueNumber       int32              `json:"github_issue_number"`
	OrderNumber             int32              `json:"order_number"`
	GithubIssueUrl          pgtype.Text        `json:"github_issue_url"`
	GithubUsername          string             `json:"github_username"`
	Sku                     string             `json:"sku"`
	Options                 []byte             `json:"options"`
	SubtotalCents           int32              `json:"subtotal_cents"`
	ShippingCents           int32              `json:"shipping_cents"`
	TaxCents                pgtype.Int4        `json:"tax_cents"`
	TotalCents              int32              `json:"total_cents"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   pgtype.Text        `json:"stripe_payment_intent_id"`
	CustomerEmail           pgtype.Text        `json:"customer_email"`
	CustomerName            pgtype.Text        `json:"customer_name"`
	ShippingAddress         []byte             `json:"shipping_address"`
	TrackingNumber          pgtype.Text        `json:"tracking_number"`
	TrackingUrl             pgtype.Text        `json:"tracking_url"`
	Carrier                 pgtype.Text        `json:"carrier"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	ShippedAt               pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt             pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) GetOrderByStripeSessionID(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (GetOrderByStripeSessionIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByStripeSessionID, stripeCheckoutSessionID)
	var i GetOrderByStripeSessionIDRow
	err := row.Scan(
		&i.ID,
		&i.ShopID,
		&i.GithubIssueNumber,
		&i.OrderNumber,
		&i.GithubIssueUrl,
		&i.GithubUsername,
		&i.Sku,
		&i.Options,
		&i.SubtotalCents,
		&i.ShippingCents,
		&i.TaxCents,
		&i.TotalCents,
		&i.StripeCheckoutSessionID,
		&i.StripePaymentIntentID,
		&i.CustomerEmail,
		&i.CustomerName,
		&i.ShippingAddress,
		&i.TrackingNumber,
		&i.TrackingUrl,
		&i.Carrier,
		&i.Status,
		&i.CreatedAt,
		&i.PaidAt,
		&i.ShippedAt,
		&i.DeliveredAt,
	)
	return i, err
}

const getOrdersByShop = `-- name: GetOrdersByShop :many
SELECT id, shop_id, github_issue_number, order_number, github_issue_url, github_username, sku,
       options, subtotal_cents, shipping_cents, tax_cents, total_cents,
       stripe_checkout_session_id, stripe_payment_intent_id, customer_email, customer_name,
       shipping_address, tracking_number, tracking_url, carrier, status,
       created_at, paid_at, shipped_at, delivered_at
FROM orders 
WHERE shop_id = $1 
ORDER BY created_at DESC 
LIMIT $2
`

type GetOrdersByShopParams struct {
	ShopID uuid.UUID `json:"shop_id"`
	Limit  int32     `json:"limit"`
}

type GetOrdersByShopRow struct {
	ID                      uuid.UUID          `json:"id"`
	ShopID                  uuid.UUID          `json:"shop_id"`
	GithubIssueNumber       int32              `json:"github_issue_number"`
	OrderNumber             int32              `json:"order_number"`
	GithubIssueUrl          pgtype.Text        `json:"github_issue_url"`
	GithubUsername          string             `json:"github_username"`
	Sku                     string             `json:"sku"`
	Options                 []byte             `json:"options"`
	SubtotalCents           int32              `json:"subtotal_cents"`
	ShippingCents           int32              `json:"shipping_cents"`
	TaxCents                pgtype.Int4        `json:"tax_cents"`
	TotalCents              int32              `json:"total_cents"`
	StripeCheckoutSessionID pgtype.Text        `json:"stripe_checkout_session_id"`
	StripePaymentIntentID   pgtype.Text        `json:"stripe_payment_intent_id"`
	CustomerEmail           pgtype.Text        `json:"customer_email"`
	CustomerName            pgtype.Text        `json:"customer_name"`
	ShippingAddress         []byte             `json:"shipping_address"`
	TrackingNumber          pgtype.Text        `json:"tracking_number"`
	TrackingUrl             pgtype.Text        `json:"tracking_url"`
	Carrier                 pgtype.Text        `json:"carrier"`
	Status                  string             `json:"status"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PaidAt                  pgtype.Timestamptz `json:"paid_at"`
	ShippedAt               pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt             pgtype.Timestamptz `json:"delivered_at"`
}

func (q *Queries) GetOrdersByShop(ctx context.Context, arg GetOrdersByShopParams) ([]GetOrdersByShopRow, error) {
	rows, err := q.db.Query(ctx, getOrdersByShop, arg.ShopID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersByShopRow
	for rows.Next() {
		var i GetOrdersByShopRow
		if err := rows.Scan(
			&i.ID,
			&i.ShopID,
			&i.GithubIssueNumber,
			&i.OrderNumber,
			&i.GithubIssueUrl,
			&i.GithubUsername,
			&i.Sku,
			&i.Options,
			&i.SubtotalCents,
			&i.ShippingCents,
			&i.TaxCents,
			&i.TotalCents,
			&i.StripeCheckoutSessionID,
			&i.StripePaymentIntentID,
			&i.CustomerEmail,
			&i.CustomerName,
			&i.ShippingAddress,
			&i.TrackingNumber,
			&i.TrackingUrl,
			&i.Carrier,
			&i.Status,
			&i.CreatedAt,
			&i.PaidAt,
			&i.ShippedAt,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderDelivered = `-- name: UpdateOrderDelivered :exec
UPDATE orders 
SET status = 'delivered', delivered_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateOrderDelivered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateOrderDelivered, id)
	return err
}

const updateOrderPaid = `-- name: UpdateOrderPaid :exec
UPDATE orders 
SET status = 'paid', paid_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateOrderPaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateOrderPaid, id)
	return err
}

const updateOrderShipping = `-- name: UpdateOrderShipping :exec
UPDATE orders 
SET status = 'shipped', tracking_number = $2, carrier = $3, shipped_at = NOW()
WHERE id = $1
`

type UpdateOrderShippingParams struct {
	ID             uuid.UUID   `json:"id"`
	TrackingNumber pgtype.Text `json:"tracking_number"`
	Carrier        pgtype.Text `json:"carrier"`
}

func (q *Queries) UpdateOrderShipping(ctx context.Context, arg UpdateOrderShippingParams) error {
	_, err := q.db.Exec(ctx, updateOrderShipping, arg.ID, arg.TrackingNumber, arg.Carrier)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders 
SET status = $2
WHERE id = $1
`

type UpdateOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.ID, arg.Status)
	return err
}
