// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountShopsByInstallationID(ctx context.Context, githubInstallationID int64) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error)
	DisconnectShop(ctx context.Context, arg DisconnectShopParams) error
	GetConnectedShopsByInstallationID(ctx context.Context, githubInstallationID int64) ([]Shop, error)
	GetDistinctInstallationIDs(ctx context.Context) ([]int64, error)
	GetFirstConfiguredShop(ctx context.Context, githubInstallationID int64) (Shop, error)
	GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error)
	GetOrderByIssueNumber(ctx context.Context, arg GetOrderByIssueNumberParams) (GetOrderByIssueNumberRow, error)
	GetOrderByStripeSessionID(ctx context.Context, stripeCheckoutSessionID pgtype.Text) (GetOrderByStripeSessionIDRow, error)
	GetOrdersByShop(ctx context.Context, arg GetOrdersByShopParams) ([]GetOrdersByShopRow, error)
	GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error)
	GetShopByInstallationAndRepoID(ctx context.Context, arg GetShopByInstallationAndRepoIDParams) (Shop, error)
	GetShopByInstallationID(ctx context.Context, githubInstallationID int64) (Shop, error)
	GetShopByRepoID(ctx context.Context, githubRepoID int64) (Shop, error)
	GetShopsByInstallationID(ctx context.Context, githubInstallationID int64) ([]Shop, error)
	ReconnectShop(ctx context.Context, arg ReconnectShopParams) error
	UpdateOrderDelivered(ctx context.Context, id uuid.UUID) error
	UpdateOrderPaid(ctx context.Context, id uuid.UUID) error
	UpdateOrderShipping(ctx context.Context, arg UpdateOrderShippingParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateShopEmailConfig(ctx context.Context, arg UpdateShopEmailConfigParams) error
	UpdateShopRepoFullName(ctx context.Context, arg UpdateShopRepoFullNameParams) error
	UpdateShopStripeConnectAccount(ctx context.Context, arg UpdateShopStripeConnectAccountParams) error
}

var _ Querier = (*Queries)(nil)
