// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shops.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countShopsByInstallationID = `-- name: CountShopsByInstallationID :one
SELECT COUNT(*) FROM shops WHERE github_installation_id = $1
`

func (q *Queries) CountShopsByInstallationID(ctx context.Context, githubInstallationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countShopsByInstallationID, githubInstallationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShop = `-- name: CreateShop :one
INSERT INTO shops (github_installation_id, github_repo_id, github_repo_full_name, owner_email)
VALUES ($1, $2, $3, $4)
RETURNING id, github_installation_id, github_repo_id, github_repo_full_name, owner_email,
          email_provider, email_config, email_verified,
          stripe_connect_account_id, disconnected_at, created_at, updated_at
`

type CreateShopParams struct {
	GithubInstallationID int64  `json:"github_installation_id"`
	GithubRepoID         int64  `json:"github_repo_id"`
	GithubRepoFullName   string `json:"github_repo_full_name"`
	OwnerEmail           string `json:"owner_email"`
}

func (q *Queries) CreateShop(ctx context.Context, arg CreateShopParams) (Shop, error) {
	row := q.db.QueryRow(ctx, createShop,
		arg.GithubInstallationID,
		arg.GithubRepoID,
		arg.GithubRepoFullName,
		arg.OwnerEmail,
	)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.OwnerEmail,
		&i.EmailProvider,
		&i.EmailConfig,
		&i.EmailVerified,
		&i.StripeConnectAccountID,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disconnectShop = `-- name: DisconnectShop :exec
UPDATE shops
SET disconnected_at = NOW(),
    stripe_connect_account_id = NULL,
    email_config = '{}',
    email_verified = FALSE,
    updated_at = NOW()
WHERE github_installation_id = $1 AND github_repo_id = $2
`

type DisconnectShopParams struct {
	GithubInstallationID int64 `json:"github_installation_id"`
	GithubRepoID         int64 `json:"github_repo_id"`
}

func (q *Queries) DisconnectShop(ctx context.Context, arg DisconnectShopParams) error {
	_, err := q.db.Exec(ctx, disconnectShop, arg.GithubInstallationID, arg.GithubRepoID)
	return err
}

const getConnectedShopsByInstallationID = `-- name: GetConnectedShopsByInstallationID :many
SELECT id, github_installation_id, github_repo_id, github_repo_full_name, owner_email,
       email_provider, email_config, email_verified,
       stripe_connect_account_id, disconnected_at, created_at, updated_at
FROM shops
WHERE github_installation_id = $1 AND disconnected_at IS NULL
ORDER BY github_repo_full_name
`

func (q *Queries) GetConnectedShopsByInstallationID(ctx context.Context, githubInstallationID int64) ([]Shop, error) {
	rows, err := q.db.Query(ctx, getConnectedShopsByInstallationID, githubInstallationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.GithubInstallationID,
			&i.GithubRepoID,
			&i.GithubRepoFullName,
			&i.OwnerEmail,
			&i.EmailProvider,
			&i.EmailConfig,
			&i.EmailVerified,
			&i.StripeConnectAccountID,
			&i.DisconnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctInstallationIDs = `-- name: GetDistinctInstallationIDs :many
SELECT DISTINCT github_installation_id FROM shops WHERE github_installation_id IS NOT NULL
`

func (q *Queries) GetDistinctInstallationIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, getDistinctInstallationIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var github_installation_id int64
		if err := rows.Scan(&github_installation_id); err != nil {
			return nil, err
		}
		items = append(items, github_installation_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstConfiguredShop = `-- name: GetFirstConfiguredShop :one
SELECT id, github_installation_id, github_repo_id, github_repo_full_name, owner_email,
       email_provider, email_config, email_verified,
       stripe_connect_account_id, disconnected_at, created_at, updated_at
FROM shops
WHERE github_installation_id = $1
  AND stripe_connect_account_id IS NOT NULL
  AND email_verified = true
LIMIT 1
`

func (q *Queries) GetFirstConfiguredShop(ctx context.Context, githubInstallationID int64) (Shop, error) {
	row := q.db.QueryRow(ctx, getFirstConfiguredShop, githubInstallationID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.OwnerEmail,
		&i.EmailProvider,
		&i.EmailConfig,
		&i.EmailVerified,
		&i.StripeConnectAccountID,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByID = `-- name: GetShopByID :one
SELECT id, github_installation_id, github_repo_id, github_repo_full_name, owner_email,
       email_provider, email_config, email_verified,
       stripe_connect_account_id, disconnected_at, created_at, updated_at
FROM shops
WHERE id = $1
`

func (q *Queries) GetShopByID(ctx context.Context, id uuid.UUID) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByID, id)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.OwnerEmail,
		&i.EmailProvider,
		&i.EmailConfig,
		&i.EmailVerified,
		&i.StripeConnectAccountID,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByInstallationAndRepoID = `-- name: GetShopByInstallationAndRepoID :one
SELECT id, github_installation_id, github_repo_id, github_repo_full_name, owner_email,
       email_provider, email_config, email_verified,
       stripe_connect_account_id, disconnected_at, created_at, updated_at
FROM shops
WHERE github_installation_id = $1 AND github_repo_id = $2
`

type GetShopByInstallationAndRepoIDParams struct {
	GithubInstallationID int64 `json:"github_installation_id"`
	GithubRepoID         int64 `json:"github_repo_id"`
}

func (q *Queries) GetShopByInstallationAndRepoID(ctx context.Context, arg GetShopByInstallationAndRepoIDParams) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByInstallationAndRepoID, arg.GithubInstallationID, arg.GithubRepoID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.OwnerEmail,
		&i.EmailProvider,
		&i.EmailConfig,
		&i.EmailVerified,
		&i.StripeConnectAccountID,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByInstallationID = `-- name: GetShopByInstallationID :one
SELECT id, github_installation_id, github_repo_id, github_repo_full_name, owner_email,
       email_provider, email_config, email_verified,
       stripe_connect_account_id, disconnected_at, created_at, updated_at
FROM shops
WHERE github_installation_id = $1
`

func (q *Queries) GetShopByInstallationID(ctx context.Context, githubInstallationID int64) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByInstallationID, githubInstallationID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.OwnerEmail,
		&i.EmailProvider,
		&i.EmailConfig,
		&i.EmailVerified,
		&i.StripeConnectAccountID,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopByRepoID = `-- name: GetShopByRepoID :one
SELECT id, github_installation_id, github_repo_id, github_repo_full_name, owner_email,
       email_provider, email_config, email_verified,
       stripe_connect_account_id, disconnected_at, created_at, updated_at
FROM shops
WHERE github_repo_id = $1
`

func (q *Queries) GetShopByRepoID(ctx context.Context, githubRepoID int64) (Shop, error) {
	row := q.db.QueryRow(ctx, getShopByRepoID, githubRepoID)
	var i Shop
	err := row.Scan(
		&i.ID,
		&i.GithubInstallationID,
		&i.GithubRepoID,
		&i.GithubRepoFullName,
		&i.OwnerEmail,
		&i.EmailProvider,
		&i.EmailConfig,
		&i.EmailVerified,
		&i.StripeConnectAccountID,
		&i.DisconnectedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShopsByInstallationID = `-- name: GetShopsByInstallationID :many
SELECT id, github_installation_id, github_repo_id, github_repo_full_name, owner_email,
       email_provider, email_config, email_verified,
       stripe_connect_account_id, disconnected_at, created_at, updated_at
FROM shops
WHERE github_installation_id = $1
ORDER BY github_repo_full_name
`

func (q *Queries) GetShopsByInstallationID(ctx context.Context, githubInstallationID int64) ([]Shop, error) {
	rows, err := q.db.Query(ctx, getShopsByInstallationID, githubInstallationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shop
	for rows.Next() {
		var i Shop
		if err := rows.Scan(
			&i.ID,
			&i.GithubInstallationID,
			&i.GithubRepoID,
			&i.GithubRepoFullName,
			&i.OwnerEmail,
			&i.EmailProvider,
			&i.EmailConfig,
			&i.EmailVerified,
			&i.StripeConnectAccountID,
			&i.DisconnectedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconnectShop = `-- name: ReconnectShop :exec
UPDATE shops
SET disconnected_at = NULL,
    updated_at = NOW()
WHERE github_installation_id = $1 AND github_repo_id = $2
`

type ReconnectShopParams struct {
	GithubInstallationID int64 `json:"github_installation_id"`
	GithubRepoID         int64 `json:"github_repo_id"`
}

func (q *Queries) ReconnectShop(ctx context.Context, arg ReconnectShopParams) error {
	_, err := q.db.Exec(ctx, reconnectShop, arg.GithubInstallationID, arg.GithubRepoID)
	return err
}

const updateShopEmailConfig = `-- name: UpdateShopEmailConfig :exec
UPDATE shops
SET email_provider = $2, email_config = $3, email_verified = $4, updated_at = NOW()
WHERE id = $1
`

type UpdateShopEmailConfigParams struct {
	ID            uuid.UUID   `json:"id"`
	EmailProvider pgtype.Text `json:"email_provider"`
	EmailConfig   []byte      `json:"email_config"`
	EmailVerified pgtype.Bool `json:"email_verified"`
}

func (q *Queries) UpdateShopEmailConfig(ctx context.Context, arg UpdateShopEmailConfigParams) error {
	_, err := q.db.Exec(ctx, updateShopEmailConfig,
		arg.ID,
		arg.EmailProvider,
		arg.EmailConfig,
		arg.EmailVerified,
	)
	return err
}

const updateShopRepoFullName = `-- name: UpdateShopRepoFullName :exec
UPDATE shops
SET github_repo_full_name = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateShopRepoFullNameParams struct {
	ID                 uuid.UUID `json:"id"`
	GithubRepoFullName string    `json:"github_repo_full_name"`
}

func (q *Queries) UpdateShopRepoFullName(ctx context.Context, arg UpdateShopRepoFullNameParams) error {
	_, err := q.db.Exec(ctx, updateShopRepoFullName, arg.ID, arg.GithubRepoFullName)
	return err
}

const updateShopStripeConnectAccount = `-- name: UpdateShopStripeConnectAccount :exec
UPDATE shops
SET stripe_connect_account_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateShopStripeConnectAccountParams struct {
	ID                     uuid.UUID   `json:"id"`
	StripeConnectAccountID pgtype.Text `json:"stripe_connect_account_id"`
}

func (q *Queries) UpdateShopStripeConnectAccount(ctx context.Context, arg UpdateShopStripeConnectAccountParams) error {
	_, err := q.db.Exec(ctx, updateShopStripeConnectAccount, arg.ID, arg.StripeConnectAccountID)
	return err
}
